### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by imanghafoori1** [WebDevEtc/BlogEtc#1]
You may use the imanghafoori1/laravel-heyman instead of the middlewares.
That way your users (if they need), can override the access restrictions how ever they in complete freedom.

**Comment by WebDevEtc** [comment]
Hi,
Thanks for the feedback. I will check it out - looks like a nice package.

**Comment by Olabayo** [comment]
Hi class view not found error, on composer dump-autoload. Resolved by moving $this->loadViewsFrom form register() to boot() function in BlogEtcServiceProvider.php

**Comment by vitasya** [comment]
Hello and thanks for the package. I have a question: is it possible to integrate uploading images (I mean public/blog_images) to AWS S3 bucket?

**Comment by imanghafoori1** [comment]
What do you mean by "integration with uploading images" ?! 

This package basically uses on events to get in,  check conditions, and react if needed.
