### ISSUE TITLE
Unpublished items are listing in search results

### ISSUE THREAD

**Issue by allyreflections** [WebDevEtc/BlogEtc#12]
Hi,

I have set the 'is_published' field to false as default for the admin approval of posts. Here my issue is the search results page showing the unpublished posts in the listing. 

Please help me to resolve this issue.

Thanks,
ALLI

**Comment by WebDevEtc** [comment]
Ok, this is a bug I will get fixed on next release. Thanks for reporting it.

**Comment by samberrry** [comment]
@allyreflections 
My pull request for this fix is approved: https://github.com/swisnl/laravel-fulltext/pull/23
I'm gonna update the packge: https://github.com/vhessam/laravel-blogger 
to fix this issue.

**Comment by WebDevEtc** [comment]
Thanks for this - I've updated this package to work with the latest version of Laravel. it can be found on webdevetc/blogetc.
