### ISSUE TITLE
Youtube video embed

### ISSUE THREAD

**Issue by wast** [WebDevEtc/BlogEtc#143]
Can't embed youtube video in blog post correctly.

Editor doesn't have video plugin installed:
![image](https://user-images.githubusercontent.com/9076227/84993529-b07e0800-b149-11ea-98c0-09069815bff0.png)

When I use generated iframe from youtube and paste it into editor without
![image](https://user-images.githubusercontent.com/9076227/84993696-e7541e00-b149-11ea-8e26-2343711025fc.png)

I get this:
![image](https://user-images.githubusercontent.com/9076227/84993738-f509a380-b149-11ea-963c-b3ac3d9336e8.png)

When I paste it as code:
![image](https://user-images.githubusercontent.com/9076227/84993869-22565180-b14a-11ea-89b6-9c1007a51960.png)

I get this:
![image](https://user-images.githubusercontent.com/9076227/84994242-b45e5a00-b14a-11ea-96e3-9d93c1b70634.png)

But, when I go edit that post:
![image](https://user-images.githubusercontent.com/9076227/84994282-c17b4900-b14a-11ea-96dd-2dc3c51ed717.png)
and
![image](https://user-images.githubusercontent.com/9076227/84994301-c809c080-b14a-11ea-82e5-31f6d18aad87.png)

Is there other solution? Can I add video plugin somehow? Documentation is small. 
Also video is not responsive.

**Comment by samberrry** [comment]
hi @wast, 
this issue is fixed on this package: https://packagist.org/packages/hessam/laravel-blogger
Also this package has an updated and rich text editor.
I try to support it as much as possible and quickly fix bugs.

How to install: https://hessam.binshops.com/laravel-blog-package/

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20775532/85018089-d9ba8a80-b181-11ea-9afc-2cb8a4dae09d.gif)

**Comment by wast** [comment]
So it won't be fixed in this package ? 
What's the difference between 2 packages?

**Comment by samberrry** [comment]
@wast 
the main difference is support as you see. As soon as a problem is arised I start work to fix it.
I made this package compatible with Laravel 6 and higher and fixed many issues. And plus, I'm gonna add more features to the package.

**Comment by WebDevEtc** [comment]
This package is the main one, the other package is a fork.

@vhessam you are welcome to do a PR for this. I can add you as a contributor on this project. Having two locations is just confusing.

**Comment by samberrry** [comment]
@WebDevEtc 
Yes, and I gave this suggestion before. I should think more about it, because since then I made some contents and development.. Anyway it's a pleasure many thanks.

**Comment by samberrry** [comment]
@wast 
https://packagist.org/packages/hessam/laravel-blogger
ability to remove photos is added in 7.1.8 version . Now you can use it for newly created posts. 
many thanks

**Comment by WebDevEtc** [comment]
Fixed in latest release (v8.1.0). 

Again, this is on the main repo (https://github.com/WebDevEtc/BlogEtc) which is still being worked on.
