### ISSUE TITLE
Remove image feature

### ISSUE THREAD

**Issue by wast** [WebDevEtc/BlogEtc#144]
I don't see a way to remove uploaded image.

![image](https://user-images.githubusercontent.com/9076227/85017716-4034ae00-b16c-11ea-90df-fe44eb05e329.png)

Am I missing something or it's a missing feature?

**Comment by samberrry** [comment]
@wast 
Lack of this feature. I'm gonna add this feature soon.

**Comment by samberrry** [comment]
@wast 
this feature is added, you can use it ;)
https://github.com/vhessam/laravel-blogger

**Comment by WebDevEtc** [comment]
@wast - this feature is part of the latest release for this package (v8), you can now delete featured images for a post.
see https://packagist.org/packages/webdevetc/blogetc
(the vhessam/laravel-blogger is a different fork)
