### ISSUE TITLE
Query for .env file

### ISSUE THREAD

**Issue by 2015pgcaca44** [WebDevEtc/BlogEtc#146]
Hi Sir,
I have cloned the project. When i'm trying to to install the composer i'm not getting .env file.
I'm using composer install command 
how can i get the file please help?

My Laravel version is 7.1 and PHP version 7.3.7

email: nitesh182185048@gmail.com

**Comment by samberrry** [comment]
Hi @2015pgcaca44,
the .env file is for your entire laravel project not this package. 

I made this package compatible with Laravel 6 and higher as well through another package: https://github.com/vhessam/laravel-blogger

thanks

**Comment by samberrry** [comment]
https://hessam.binshops.com/laravel-blog-package/

**Comment by WebDevEtc** [comment]
This package here is fully compatible with the latest laravel versions.
The .env thing is not related to an issue with this package though. You need to install laravel, then install this package.
