### ISSUE TITLE
The post per page config value is not taken into account

### ISSUE THREAD

**Issue by WEBDeon** [WebDevEtc/BlogEtc#147]
**Describe the bug**
The post per page config value is not taken into account. If you change the value in the config file there are still 10 posts per page.

**How to fix it**
In vendor\webdevetc\blogetc\src\Controllers\PostsController.php line 108
"$posts = $this->postsService->indexPaginated(config('blogetc.per_page'), $categoryID);"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WebDevEtc** [comment]
Hi! thanks for this! Just about to fix it!
