### ISSUE TITLE
How change layout blog_admin ?

### ISSUE THREAD

**Issue by rickymerby** [WebDevEtc/BlogEtc#15]
Can i change stylesheet of blog admin ?

**Comment by stillatmylinux** [comment]
You just need to copy the files from 

`vendor/webdevetc/blogetc/src/Views/blogetc_admin`

to

`resources/views/vendor/blogetc_admin`

Then you can modify them just like any other view file.

**Comment by WebDevEtc** [comment]
Thanks @stillatmylinux - that is the answer that I would have given too. 
The view files are all referenced like view('blogetc_admin::some-view'), and the 'blogetc_admin::' view dir is registered... Laravel will look in normal /resources/views/vendor/blogetc_admin dir, if not found then it will look in /vendor/webdevetc/blogetc/...
