### ISSUE TITLE
Multi-language support: Save posts in different languages

### ISSUE THREAD

**Issue by axgalache** [WebDevEtc/BlogEtc#158]
This would be very useful for a multi-language page, so then you can write in the same blog post creation page the different translations for texts and titles, and save in multiple languages.

Is there some way now to fill and save posts in different languages?

Thank you!

**Comment by vhessam** [comment]
hi @axgalache,
you can use my package: http://hessam.binshops.com/laravel-blog-package
I support it very well, also I've planned to add multi-language functionality to this package ;)

**Comment by WebDevEtc** [comment]
This would be a great feature but I feel this is out of scope of this package.
