### ISSUE TITLE
Error "The config/blogetc.php does not exist"

### ISSUE THREAD

**Issue by FRKodes** [WebDevEtc/BlogEtc#16]
I followed all the steps in the "5 Minute Install Guide" from here:

https://webdevetc.com/laravel/packages/blogetc-blog-system-for-your-laravel-app/help-documentation/laravel-blog-package-blogetc

At the end I can see the /blog page but, when I try to get the /blog_admin page I get this error.

<img width="1400" alt="Screen Shot 2019-09-16 at 9 03 46 PM" src="https://user-images.githubusercontent.com/3393727/65005706-628c5900-d8c6-11e9-96f7-509a91155003.png">

As you can see the error says there is no blogetc.php into the config folder, but as this screenshot you can see there is a file into the folder.

<img width="843" alt="Screen Shot 2019-09-16 at 9 04 38 PM" src="https://user-images.githubusercontent.com/3393727/65005731-8a7bbc80-d8c6-11e9-93d8-4e4179e8b965.png">

I have this screenshot also, where you can see I ran the command php artisan vendor:publish --provider="WebDevEtc\BlogEtc\BlogEtcServiceProvider"

<img width="930" alt="Screen Shot 2019-09-16 at 9 06 26 PM" src="https://user-images.githubusercontent.com/3393727/65005781-b39c4d00-d8c6-11e9-81ad-a3d5b4de3f51.png">

I think there is no clue, at least for me where could be the problem, I hope you can hit me up with some clue in order to fix it.

Thanks!

**Comment by WebDevEtc** [comment]
have you done `php artisan cache:clear`? That is the only thing that comes to mind.

**Comment by FRKodes** [comment]
I tried with the php artisan cache:clear command and still getting the same error :/ 

Any idea?

Thanks!

**Comment by WebDevEtc** [comment]
Have a look with `php artisan tinker` and see what `config('blogetc')` returns (it should return an array of config values...)

**Comment by FRKodes** [comment]
The command returns null :/

What am I doing wrong? Any clue?

Thanks a lot.

<img width="852" alt="Screen Shot 2020-01-09 at 11 01 57 PM" src="https://user-images.githubusercontent.com/3393727/72127143-51170300-3334-11ea-96a9-7e06ccec1180.png">

**Comment by WebDevEtc** [comment]
Closing this issue as it was from ages ago. Let me know if you are still having issues!
