### ISSUE TITLE
How to fix " Could not parse version constraint   ^6.*: Invalid version string "^6.*"" - update composer

### ISSUE THREAD

**Issue by WebDevEtc** [WebDevEtc/BlogEtc#173]
FYI - if you get an error message such as "Could not parse version constraint   ^6.*: Invalid version string "^6.*"" from `composer`, try updating composer:

`composer self-update`

(or see https://getcomposer.org/download/)

If this does not work please leave a message below.

**Comment by schuvatz** [comment]
> FYI - if you get an error message such as "Could not parse version constraint ^6._: Invalid version string "^6._"" from `composer`, try updating composer:
> 
> `composer self-update`
> 
> (or see https://getcomposer.org/download/)
> 
> If this does not work please leave a message below.

Same problem here, but the self-update not worked for me.

**Comment by brpinpe** [comment]
It doesn't work.
