### ISSUE TITLE
How to install with laravel 8.2.0?

### ISSUE THREAD

**Issue by Sir-Joker** [WebDevEtc/BlogEtc#174]
After updating with:
composer update
composer self-update
i run: composer require "webdevetc/blogetc"

Errormessage: 

Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Installation request for webdevetc/blogetc ^8.4 -> satisfiable by webdevetc/blogetc[8.4].
    - Conclusion: remove laravel/framework v8.2.0
    - Conclusion: don't install laravel/framework v8.2.0
    - webdevetc/blogetc 8.4 requires laravel/framework ~5.8|~6.0|~7.0 -> satisfiable by laravel/framework[5.8.x-dev, 6.x-dev, 7.x-dev].
    - Can only install one of: laravel/framework[5.8.x-dev, v8.2.0].
    - Can only install one of: laravel/framework[6.x-dev, v8.2.0].
    - Can only install one of: laravel/framework[7.x-dev, v8.2.0].
    - Installation request for laravel/framework (locked at v8.2.0, required as ^8.0) -> satisfiable by laravel/framework[v8.2.0].

**Comment by dezer32** [comment]
Maintainer needs to update composer.json

**Comment by WebDevEtc** [comment]
Sorry this should now work - `composer require --no-cache -vvv webdevetc/blogetc:8.4.2`. Let me know if you still have issues.
