### ISSUE TITLE
How to fix " Class 'App\Providers\GateTypes' not found "

### ISSUE THREAD

**Issue by atharali** [WebDevEtc/BlogEtc#181]
Hi,

How can we fix this will you please help me

![Capture](https://user-images.githubusercontent.com/6583912/93334937-21af8300-f83f-11ea-8cbd-5a321ade0f39.PNG)

**Comment by WebDevEtc** [comment]
Hi,
You are probably missing the namespace.

Replace `GateTypes` with `\WebDevEtc\BlogEtc\Gates\GateTypes` and let me know if that fixed it.

**Comment by WebDevEtc** [comment]
Marking as resolved - please reopen if you still have issues with the correct namespacing.

**Comment by atharali** [comment]
Hi,

It's still not working now I get this
![image](https://user-images.githubusercontent.com/6583912/93877987-cffd7180-fcf2-11ea-9e86-bb9a9081f02d.png)
