### ISSUE TITLE
Unexpected 'Gate' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by t8ysn** [WebDevEtc/BlogEtc#189]
**Describe the bug**
syntax error, unexpected 'Gate' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

I copied this into my AuthServiceProvider

  Gate::define(\WebDevEtc\BlogEtc\Gates\GateTypes::MANAGE_BLOG_ADMIN, static function(?Model $admin){
        // Implement your logic here, for example:
        return$user&&$user->email==='your-[email protected]';
        // Or something like `$user->is_admin === true`
    });

**Comment by samberrry** [comment]
@t8ysn 
check my package: 
https://github.com/vhessam/laravel-blog-package

**Comment by jerryhall** [comment]
> 
> 
> @t8ysn
> check my package:
> https://github.com/vhessam/laravel-blog-package

Hey @sam-beri could you expand on that? I'm having the same problem but, don't know well enough yet to reverse-engineer the solution. Thanks!

**Comment by careerhub-source** [comment]
Hi @t8ysn Have able to get solution concern that, since I have the same problem

**Comment by OkubeEmmanuel** [comment]
paste the code in your boot method, It should work.

**Comment by careerhub-source** [comment]
I  already solve this, but the problem now is the style not working, when
create post and post aome styles like italics, bold, h1 h2 etc is not saved
and I can not find in frontend

**Comment by tungtata** [comment]
Argument 1 passed to App\Providers\AuthServiceProvider::App\Providers\{closure}() must be an instance of App\Providers\Model or null, instance of App\Models\User given, called in D:\Documents\GitHub\Nghien.Sale\vendor\laravel\framework\src\Illuminate\Auth\Access\Gate.php on line 536

I got this error
