### ISSUE TITLE
some bugs are coming in your pack

### ISSUE THREAD

**Issue by ghost** [WebDevEtc/BlogEtc#192]
![image](https://user-images.githubusercontent.com/72428261/124755817-3fbcb000-df45-11eb-96c2-db19a3fb8094.png)
![image](https://user-images.githubusercontent.com/72428261/124755891-57943400-df45-11eb-8032-a82bcb0ab14f.png)
![image](https://user-images.githubusercontent.com/72428261/124755957-68dd4080-df45-11eb-8683-d615ef2e9298.png)

**Comment by thesea2201** [comment]
Try this
`use Illuminate\Database\Eloquent\Model;`
