### ISSUE TITLE
Class view not found on composer dump-autoload (Laravel 5.7)

### ISSUE THREAD

**Issue by Olabayo** [WebDevEtc/BlogEtc#3]
Class view not found error, on composer dump-autoload. Resolved by moving $this->loadViewsFrom form register() to boot() function in BlogEtcServiceProvider.php

Laravel 5.7

**Comment by WebDevEtc** [comment]
Oops! It shouldn't have been in register()! I'll do the quick fix over next few days. thanks for reporting it.

**Comment by Olabayo** [comment]
> Oops! It shouldn't have been in register()! I'll do the quick fix over next few days. thanks for reporting it.

You are welcome, awesome package
