### ISSUE TITLE
Resolve User class using auth config array (Suggestion)

### ISSUE THREAD

**Issue by Olabayo** [WebDevEtc/BlogEtc#4]
In BlogEtcPost.php and BlogEtcComment.php, to make reference to User model configurable.

Change code
From 
 return $this->belongsTo(User::class, 'user_id');

To
 return $this->belongsTo(config('auth.providers.users.model', App\User::class), 'user_id');

**Comment by WebDevEtc** [comment]
Nice catch, will fix it over next few days and upload a new release. thanks!

**Comment by Olabayo** [comment]
> Nice catch, will fix it over next few days and upload a new release. thanks!

You are welcome

**Comment by yespbs** [comment]
is this released?

**Comment by chrishubert** [comment]
It would be even better to use which guard we want to check the Auth against, by adding an entry in the BlogETC config file.
We are currently forcing the users providers (which is for the web guard in this case)

It's actually quite easy to implement: 
1. you can add ```'auth_guard' => 'web',``` in the config file
2. replace all the ```Auth::``` by ```Auth::guard(config("blogetc.auth_guard", 'web'))->``` in all your code

**Comment by samberrry** [comment]
@Olabayo 
I fixed these issues in this package: https://github.com/vhessam/laravel-blogger
Regards

**Comment by WebDevEtc** [comment]
New version (which isn't on packagist yet) addresses these issues. Will be released soon.
