### ISSUE TITLE
update on the release of 4.x

### ISSUE THREAD

**Issue by victoryirhirhi** [WebDevEtc/BlogEtc#50]
when we the release of blogetc version 4.x be out cause the current version does not support laravel version 6.0

**Comment by samberrry** [comment]
Does the team work on this project?

**Comment by samberrry** [comment]
@victoryirhirhi I made it compatible with laravel6.x version
https://packagist.org/packages/hessam/laravel-blogger

**Comment by victoryirhirhi** [comment]
How do you implement it with laravel 6.x

**Comment by samberrry** [comment]
@victoryirhirhi I made some changes in code and dependencies. Also I've did some refactor to the code to work better. You can test it

**Comment by victoryirhirhi** [comment]
Thanks so much

I have a little issue with admin panel
I can found route that lead to it or how to configure the admin user

**Comment by samberrry** [comment]
@victoryirhirhi 
You can configure the URL in blogetc.php config file. You can change this property: admin_prefix
And for admin user, you must add a function to your existing user model (\App\User for example).
The method you must add:

    public function canManageBlogEtcPosts()
       {
          // Enter the logic needed for your app.
          // Maybe you can just hardcode in a user id that you
          //   know is always an admin ID?

        if (       $this->id === 1
             && $this->email === "your_admin_user@your_site.com"
           ){

           // return true so this user CAN edit/post/delete
           // blog posts (and post any HTML/JS)

           return true;
        }

        // otherwise return false, so they have no access
        // to the admin panel (but can still view posts)

        return false;
    }

**Comment by victoryirhirhi** [comment]
Thanks I was able to set it up

**Comment by victoryirhirhi** [comment]
Good day sir

I have a RuntimeException which say. *Image destination path is not
writeable*

How do I go about it

**Comment by samberrry** [comment]
@victoryirhirhi 
You need to give it correct access right to images directory.

**Comment by WebDevEtc** [comment]
Thanks for this - I've updated this package to work with the latest version of Laravel. it can be found on webdevetc/blogetc.
