### ISSUE TITLE
New Blog Package for Laravel6.x and higher

### ISSUE THREAD

**Issue by samberrry** [WebDevEtc/BlogEtc#53]
I made this package compatible with laravel6.x and higher.
You can access it: [packagist link](https://packagist.org/packages/hessam/laravel-blogger)
**Github**: [Github Link](https://github.com/vhessam/laravel-blogger)

I noticed that the main developers refactors the code after version 3.1.4. So the current version on master is completely different from the latest version.

**Comment by christopherokonkwo** [comment]
That's good of you.

**Comment by vhessam** [comment]
:)

**Comment by samberrry** [comment]
@christopherokonkwo I shared my experience for analyzing different Laravel blog systems.
You can check it at my blog: https://hessam.binshops.com/story-about-laravel-blogs

**Comment by KaminoU** [comment]
@vhessam 

works like a charm, thx =)

@WebDevEtc @vhessam 

I believe that there are 2 missing important conditions in **BlogEtcReaderController@index** : 

`$posts = $posts->where('is_published', '=', 1)->where('posted_at', '<', Carbon::now()->format('Y-m-d H:i:s'))->orderBy("posted_at", "desc")->paginate(config("blogetc.per_page", 10));`

Without the **is_published** condition, and the **posted_at** condition, the draft and delayed post are listed and that is not what we do really want...

Thx for reading


Cheers

**Comment by samberrry** [comment]
@KaminoU 
I checked it. You are right, it shows the posts which specified to be not published. 
I also consider it in search.. 
I'm gonna add what you said.. 
thanks for your help

**Comment by samberrry** [comment]
@KaminoU 
I updated the package and added your snippet thank you so much.
Also I made a change on search package and made pull request.
https://github.com/swisnl/laravel-fulltext/pull/23
After my request is approved I'll update the package for its dependencies. That change will solve search page issue. 
tnx ;)

**Comment by KaminoU** [comment]
seen it (- Updating hessam/laravel-blogger (v7.0.1 => v7.0.2): Downloading (100%)
)

thx =)

**Comment by samberrry** [comment]
@KaminoU Thanks for your help :) I'm pursuing to fix problems.

**Comment by WebDevEtc** [comment]
Hey,
Thanks for doing this. I meant to release a new version months ago, but then work & life got in the way!

I've just updated this package (webdevetc/blogetc) to work with latest Laravel version.

(I dropped you an email to say thanks too )

**Comment by samberrry** [comment]
@WebDevEtc 

thanks for this too much helpful package. Light weight and very great.

**Comment by samberrry** [comment]
For legecy support it would better to refer to my [repository](https://github.com/vhessam/laravel-blogger), because I support it and fix any problems when one is reported, as you do not have too much time to see pull requests.
I work on the package and add some features too..

**Comment by samberrry** [comment]
@WebDevEtc 
I support the legacy and there is no problem, I have time to do that. You would update readme file to refer to my repo: https://github.com/vhessam/laravel-blogger or add me as a contributor for legacy support. The community will grow more if we contribute together.

Again many thanks for this useful package.

**Comment by samberrry** [comment]
I'm open to accept any suggestion.
Many thanks ;)

**Comment by WebDevEtc** [comment]
Hi 
feel free to do PRs on this package. 
I don't see any reason to split it up onto a different package, it makes upgrading for anyone a big pain - they would then have to remove webdevetc/blogetc, and then add vhessam/laravel-blogger. 
I do see the hole that I've dug myself be starting to do a big refactor. I might just slowly upgrade the current (legacy) one with the new changes bit by bit, will be easier than having a huge migration guide to a new version.

**Comment by samberrry** [comment]
yes you are right, but if you check issues.. I started the new package 1 month after my first issue.
So talking about PRs needs short time for example.. maximum 2 days..or 3 days.. when I started to change the code, community helped me to improve it really... that's why I did not work only on my local system, and I shared that through a new repository.
We all help each other to improve codes. As you see I can update code for a bug fix for a report in hours and respond to reports... and I'll work on legacy and wanna add features.. that could results the WebEtc package be out dated.
You can just focus on new version. Anyway it's up to you.

Many thanks for your valuable work.
