### ISSUE TITLE
Recent Post to fix

### ISSUE THREAD

**Issue by KaminoU** [WebDevEtc/BlogEtc#61]
Hi @WebDevEtc 

in BlogEtc/src/Views/blogetc/sitewide/recent_posts.blade.php

`@forelse(\WebDevEtc\BlogEtc\Models\BlogEtcPost::orderBy("posted_at","desc")->limit(3)->get() as $post)`

you have to change it to

`@forelse(\WebDevEtc\BlogEtc\Models\BlogEtcPost::where('is_published', '=', 1)->where('posted_at', '<', Carbon\Carbon::now()->format('Y-m-d H:i:s'))->orderBy("posted_at","desc")->limit(3)->get() as $post)`

to only post the last one supposed to be posted =)

**Comment by samberrry** [comment]
@KaminoU 
thanks for your attention
Did you mean @foreach?

**Comment by KaminoU** [comment]
nop @forelse exited contents @else noting here... @endforelse

it's a short blade for

@if (existed)
  @foreach ... @endforeach
@else
  nothing here...
@endif

**Comment by samberrry** [comment]
this is the existing code:

>  @foreach(\WebDevEtc\BlogEtc\Models\BlogEtcPost::orderBy("posted_at","desc")->limit(5)->get()` as $post)
>         <li class="nav-item">
>             <a class='nav-link' href='{{$post->url()}}'>{{$post->title}}</a>
>         </li>
>     @endforeach

@if(existed) => you mean $post object?
I think it will be ok if we add this snippet in @foreach:

\WebDevEtc\BlogEtc\Models\BlogEtcPost::where('is_published', '=', 1)->where('posted_at', '<', Carbon\Carbon::now()->format('Y-m-d H:i:s'))->orderBy("posted_at","desc")->limit(3)->get() as $post

**Comment by KaminoU** [comment]
ah yes sorry =D

Lol because I published the vendors views and change some line ^^

but yeah, it's a foreach for you =D

the only important thing here is the 2 where instruction before the oderBy instruction ^^

and sorry again for fast copy/past =D

**Comment by samberrry** [comment]
yeah,
ok nice ;)

**Comment by samberrry** [comment]
@KaminoU 
I updated the code: https://github.com/vhessam/laravel-blogger
many thanks

**Comment by KaminoU** [comment]
ill see it when I composer update he he =D

have a nice weekend

**Comment by samberrry** [comment]
:D 
you too thanks
