### ISSUE TITLE
App\User

### ISSUE THREAD

**Issue by tandacedric** [WebDevEtc/BlogEtc#63]
I haven't User class in App Package, but in App\Model\.

**Comment by samberrry** [comment]
@tandacedric no problem you can set it in config file

**Comment by samberrry** [comment]
@tandacedric you can see this package: https://github.com/vhessam/laravel-blogger
it has guides about search fixes plus support for legacy

**Comment by WebDevEtc** [comment]
Yeah this is something that can be changed in the config, by updating `user_model`
