### ISSUE TITLE
Won't install on a fresh Laravel 5.8

### ISSUE THREAD

**Issue by raoulwegat** [WebDevEtc/BlogEtc#7]
-----
composer require "webdevetc/blogetc"
Using version ^3.1 for webdevetc/blogetc
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for webdevetc/blogetc ^3.1 -> satisfiable by webdevetc/blogetc[v3.1].
    - Conclusion: remove laravel/framework v5.8.11
    - Conclusion: don't install laravel/framework v5.8.11
    - webdevetc/blogetc v3.1 requires illuminate/database ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by illuminate/database[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - don't install illuminate/database 5.5.x-dev|don't install laravel/framework v5.8.11
    - don't install illuminate/database 5.6.x-dev|don't install laravel/framework v5.8.11
    - don't install illuminate/database 5.7.17|don't install laravel/framework v5.8.11
    - don't install illuminate/database 5.7.18|don't install laravel/framework v5.8.11
    - don't install illuminate/database 5.7.19|don't install laravel/framework v5.8.11
    - don't install illuminate/database 5.7.x-dev|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.0|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.16|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.17|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.2|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.28|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.33|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.34|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.35|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.36|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.37|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.39|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.40|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.41|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.43|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.5.44|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.0|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.1|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.10|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.11|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.12|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.13|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.14|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.15|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.16|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.17|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.19|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.2|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.20|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.21|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.22|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.23|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.24|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.25|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.26|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.27|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.28|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.29|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.3|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.30|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.31|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.32|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.33|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.34|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.35|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.36|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.37|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.38|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.39|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.4|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.5|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.6|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.7|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.8|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.6.9|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.0|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.1|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.10|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.11|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.15|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.2|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.20|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.21|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.22|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.23|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.26|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.27|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.28|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.3|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.4|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.5|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.6|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.7|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.8|don't install laravel/framework v5.8.11
    - don't install illuminate/database v5.7.9|don't install laravel/framework v5.8.11
    - Installation request for laravel/framework (locked at v5.8.11, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.11].

Installation failed, reverting ./composer.json to its original content.
-----

Thanks,
Raoul

**Comment by shsaleh** [comment]
hi , same problem

**Comment by WEBDeon** [comment]
I made a pull request but you can update your composer.json file to use it with Laravel 5.8.x
[https://github.com/WebDevEtc/BlogEtc/pull/11/files]([https://github.com/WebDevEtc/BlogEtc/pull/11/files])

I just test it basically and must perform more in depth test but it seems OK

**Comment by DevAccess** [comment]
How can I update my own composer.json to use it with the latest Laravel? Is it some kind of override? Thank you.

**Comment by WEBDeon** [comment]
Yes it's another package actually (waiting the acceptation of my pull request).
You can easily make a copy of the package on your dev root and create a link in composer.json to use the local copy of the package (feel free to rename it if needed).

If you need more information don't hesitate to ask me.

**Comment by anilkoeri** [comment]
I tried to update composer and fork repository. Added repository to application composer file.. it install package successfully but when I run php artisan vendor:publish --provider="WebDevEtc\BlogEtc\BlogEtcServiceProvider" nothing generating.. Please help to fix it.
Thanks

**Comment by WEBDeon** [comment]
In which directory do you run the php artisan command?

**Comment by anilkoeri** [comment]
I am running my application folder. 

I forked to https://github.com/anilkoeri/BlogEtc and made changes here after that I added these to my application composer. Please let me know if I am missing anything.

`"repositories": {
        "adonix": {
            "type": "package",
            "package": {
                "name": "WebDevEtc/BlogEtc",
                "version": "master",
                "source": {
                    "url": "https://github.com/anilkoeri/BlogEtc.git",
                    "type": "git",
                    "reference":"master"
                }
            }
        }
    },

"require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laracasts/flash": "^3.0",
        "laravel/cashier": "^9.3",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "~5.8",
        "WebDevEtc/BlogEtc": "master"
    },`

**Comment by cavewebs** [comment]
I ran into the same challenges, any update yet on this?

**Comment by WEBDeon** [comment]
If not yet updated please use this one : https://github.com/WEBDeon/BlogEtc

**Comment by WebDevEtc** [comment]
Updated composer - sorry about the delay.
Currently rewriting some bits for a v4 release, taking a bit longer than anticipated 
https://packagist.org/packages/webdevetc/blogetc#v3.1.2
