### ISSUE TITLE
Hey Dude! 

### ISSUE THREAD

**Issue by samberrry** [WebDevEtc/BlogEtc#74]
Hey dude,
You are really do a DDOS on gmail and blowing up my inbox :D 
Should I stop working on repo! Or what! 

![Screen Shot 2020-05-17 at 10 20 33 PM](https://user-images.githubusercontent.com/20775532/82155883-2a8e4900-988d-11ea-8e20-449344f2cf27.png)

**Comment by WebDevEtc** [comment]
Haha sorry, was updating a few things.

I moved the code that was in master (the 'next' version - a big rewrite) into a separate branch and just set master to the 'legacy' one. So there is no legacy now, just master and the 'next' version.
